CREATE TABLE oha_hospital_databank (		
aha_id	INTEGER	,
month	INTEGER	,
quarter	INTEGER	,
year	INTEGER	,
admissions_from_ed	INTEGER	,
ambulatory_surgery_visits	INTEGER	,
available_beds	INTEGER	,
bad_debt	NUMERIC	,
benefit_expense	NUMERIC	,
births	INTEGER	,
capitated_payments	INTEGER	,
cash_short_term_investments	NUMERIC	,
charges_acute_inpatient	INTEGER	,
charges_acute_outpatient	INTEGER	,
charges_of_dpu	INTEGER	,
charges_of_home_health	INTEGER	,
charges_of_subacute_ltc	INTEGER	,
charges_of_swing_bed	INTEGER	,
charity_care	INTEGER	,
contractuals_of_acute	INTEGER	,
contractuals_of_other	INTEGER	,
depreciation_expense	NUMERIC	,
discharges_of_acute_inpatient	INTEGER	,
discharges_of_dpu	INTEGER	,
discharges_of_subacute_ltc	INTEGER	,
discharges_of_swing_bed	INTEGER	,
emergency_department_visits	INTEGER	,
facility_payroll_amount	NUMERIC	,
facility_payroll_hours	NUMERIC	,
gross_patient_accounts_receivable	NUMERIC	,
home_health_visits	INTEGER	,
incentive_payments	NUMERIC	,
inpatient_discharges	INTEGER	,
inpatient_surgeries	INTEGER	,
interest_expense	NUMERIC	,
licensed_beds	INTEGER	,
net_nonoperating_gains	NUMERIC	,
net_patient_revenue	NUMERIC	,
newborn_patient_days	INTEGER	,
non_operating_expense	NUMERIC	,
non_operating_revenue	NUMERIC	,
observation_visits	INTEGER	,
operating_margin	NUMERIC	,
other_expense	NUMERIC	,
other_operating_revenue	NUMERIC	,
other_outpatient_visits	INTEGER	,
patient_days_of_acute_inpatient	INTEGER	,
patient_days_of_dpu	INTEGER	,
patient_days_of_subacute_ltc	INTEGER	,
patient_days_of_swing_bed	INTEGER	,
payer_mix_commercial	DECIMAL(5,4)	,
payer_mix_medicaid	DECIMAL(5,4)	,
payer_mix_medicare	DECIMAL(5,4)	,
payer_mix_others	DECIMAL(5,4)	,
payer_mix_self_pay	DECIMAL(5,4)	,
physician_payroll_amount	NUMERIC	,
physician_payroll_hours	NUMERIC	,
supply_expense	NUMERIC	,
tax_subsidies	NUMERIC	,
total_charges	NUMERIC	,
total_contractual_allowances	NUMERIC	,
total_discharges	NUMERIC	,
total_margin	NUMERIC	,
total_operating_expense	NUMERIC	,
total_operating_revenue	NUMERIC	,
total_outpatient_visits	INTEGER	,
total_patient_days	INTEGER	,
total_payroll_amount	NUMERIC	,
total_payroll_hours	NUMERIC	,
total_revenue	NUMERIC	,
uncompensated_care	NUMERIC	);

CREATE TABLE ref_hospital (		
aha_id	INTEGER PRIMARY KEY	,
hospital_name	VARCHAR (255)	,
hospital_name_short	VARCHAR (255)	,
type	VARCHAR (255)	,
critical_access	BOOLEAN	,
congressional_district	INTEGER	,
county	VARCHAR (255)	,
frontier	BOOLEAN	);